import pyautogui
from win32api  import GetSystemMetrics
import os
print("SalesMate+Backup Menu Test")
print("Create a Database Backup directory called SMP")
path="D:/SMP"
if not os.path.exists(path):
    os.makedirs(path)
    #get the width and height of the monitor
width=GetSystemMetrics(0)
height=GetSystemMetrics(1)
pyautogui.FAILSAFE=False
#Print on the bottom left to launch the start menu
print("click on the bottom left  to launch the start menu ")
pyautogui.click(0,height)

print("select the salesmate+ application")
pyautogui.typewrite("salesmate+")
print("press enter key to launch salesmate+ application and wait for 10s")
pyautogui.press("enter",1,10)
print("press enter key again to close the tip of the day dialog")

pyautogui.press("enter")
print("now alt and f shortcut key in salesmate to invoke the file root menu")
pyautogui.press(['alt','f'])
print("press b to invoke the backup folder dialogue")
pyautogui.press("b")
print("Go to D Drive")
pyautogui.press("n",1,1)
print("press Right arrow key to Expand the Tree")
print("press Right arrow key to Expand the Tree")
pyautogui.press("right",1,1)
print("Go to SMP Folder")
pyautogui.typewrite("smp")
print("press Enter key to Back Up Data")
pyautogui.press("enter",1,2)
print("Press enter again to close the OK Button")
pyautogui.press("enter")
print("press alt and v to open view menu")

pyautogui.press(['alt','v'])
print("press Right arrow key 2 times to select the  setup tree ")
pyautogui.press("right",2,1)
print("press v to select the  service master in setup tree ")
pyautogui.press("v",1,2)
print("press n to select the new from sevice details ")
pyautogui.press("n",1,2)
print("print service id ")

pyautogui.press("enter")
print("print service name ")
pyautogui.typewrite("Lunch")
pyautogui.press("enter")
print("print description ")
pyautogui.typewrite("500 Persons")
pyautogui.press("enter")
print("std rate ")
pyautogui.typewrite("150")
pyautogui.press("enter",3,2)
pyautogui.press("c",1,2)
print("select customer menu  ")
pyautogui.press(['alt','c'])
print("select add customer menu  ")
pyautogui.press("a",1,2)
pyautogui.press("enter",2,2)
print("select add first name  ")
pyautogui.typewrite("xyz1")
pyautogui.press("enter",11,1)
pyautogui.press("esc",1,2)
pyautogui.press("enter",2,2)